### ISSUE TITLE
502 - Web server received an invalid response while acting as a gateway or proxy server.

### ISSUE THREAD

**Issue by JereToledoCN** [iShi0n/veeder-root-tls#3]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**

Hola! Tengo el siguiente error cuando intento obtener todos los tanques desde mi TLS4

> **502 - Web server received an invalid response while acting as a gateway or proxy server.**
> There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

Estas lineas ejecuta mi codigo:

```
const tls = new Tls('mi-ip-tls4',puerto-tls4);
const responseTanks = await tls.getTanks();
console.log(responseTanks);
```

Pero al ejecutarlo recibo el error detallado mas arriba. Cual puede ser mi falla? 

Aguardo respuestas. Muchas gracias

**Comment by nezzzumi** [comment]
Hi, @JereToledoCN.

Maybe the TLS4 port or ip is not correct. 

By default, the port is 10001, did you test the connection with this port?

This error message seems to be from a web server or a reverse proxy.

These devices usually also have a web page where we can monitor some information from the tank. The port used for this web server is not the same port we use to communicate.

Please test with port 10001 and check if it works. 🙂

**Comment by JereToledoCN** [comment]
> Hi, @JereToledoCN.
> 
> Maybe the TLS4 port or ip is not correct.
> 
> By default, the port is 10001, did you test the connection with this port?
> 
> This error message seems to be from a web server or a reverse proxy.
> 
> These devices usually also have a web page where we can monitor some information from the tank. The port used for this web server is not the same port we use to communicate.
> 
> Please test with port 10001 and check if it works. 🙂

Hola! muchas gracias por la rapida respuesta y felicitaciones por tu trabajo!

Si uso el puerto 10001 obtengo el siguiente error:

> events.js:292
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: connect ECONNREFUSED 181.10.130.120:10001
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
> Emitted 'error' event on Socket instance at:
>     at emitErrorNT (internal/streams/destroy.js:106:8)
>     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
>   errno: -4078,
>   code: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: <mi-ip>,
>   port: 10001 

Anteriormente estaba usando el puerto de la pagina web pero como tu dijiste, ese tampoco es. 

Quizas pueda ser una configuracion en la consola TLS y por eso es que no me deja acceder?

Saludos!

**Comment by nezzzumi** [comment]
Hello my friend.

I would recommend you to check if port 10001 is open on this IP with some tool (like [nmap](https://nmap.org/download.html)).

It looks like this port is closed.
